[package]
name = "simple_deck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
streamdeck = { version = "0.7.0", path = "../rust-streamdeck-updated" }
tracing-subscriber = "0.3.17"
